SLVSCODE-953 untar eslint-bridge bundle and send its path to slls
SonarSource/sonarlint-vscode pull request #659
Opened 2024-12-06 14:49 UTC by sophio-japharidze-sonarsource

2024-12-09 15:35 UTC, jblievremont requested changes
Looks good on the functional side (and tested manually); let's make sure that we are not sending anything unnecessary in the telemetry payload 😅

2024-12-09 15:35 UTC, jblievremont commented on src/extension.ts
> +          eslintBridgeServerPath: Path.resolve(context.extensionPath, 'eslint-bridge')
See my comment on SLLS: the `additionalAttributes` field is sent as-is to the telemetry, so I believe it needs to be renamed and cleaned-up.

2024-12-10 07:59 UTC, jblievremont approved these changes
LGTM ⏩!

2024-12-10 10:41 UTC, closed without merging

2024-12-10 10:41 UTC, sophio-japharidze-sonarsource commented
Superseded by #661